baseURL = 'https://example.org/'
locale = 'en-us'
title = 'KHO KINH HÁN VIỆT'
theme = 'hugo-book' 
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
[params]
  BookCustomCSS = ["_custom.css"]
[params]
  # Đảm bảo cột bên phải (TOC) luôn hiển thị
  BookToC = true
